services:
  - type: web
    name: cricket-api
    env: python
    plan: free
    buildCommand: pip install -r fastapi-cricket/requirements.txt
    startCommand: uvicorn fastapi-cricket.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    branch: main
